#!/bin/bash
set -e

# Create the initial cache on first install
if [ "$1" = "configure" ]; then
    echo "fuzzpm: Building initial package cache..."
    sudo /usr/local/bin/fpm --refresh
    echo "fuzzpm: Done."
fi

exit 0
